### ISSUE TITLE
Lost focus with SlickGrid+OpenLayers

### ISSUE THREAD

**Issue by kvirkeson** [RickStrahl/jquery-resizable#12]
Hi,

I am using the plugin in combination with SlickGrid (left panel) and OpenLayers V2.13.1 (right panel).
 When I slide to the left, it works as expected,  but  in  opposite  direction,  the mouse loses focus on the
splitter  in  the middle when I move fast to the right side (the mouse
drifts onto the map, which makes the map get focus). But the dragEnd event isn't
fired  yet...when  I move back to the splitter by a mouse movement, you see that the splitter still  has
control,  I  am able  to move it until I actually press the mouse button again (which triggers the dragEnd event).

p.s.:  I am not using any iframe or update operations on the map,

**Comment by RickStrahl** [comment]
That sounds like what you see with iframe and if you're using a map control like Google Maps it actually internally renders into an iframe. I don't know of a good way around this - the problem is that an iframe is slow to resize and when it gets focus steal focus from the host frame. That's why the cursor detaches. I don't have a work around for this unfortunately.

**Comment by kvirkeson** [comment]
Oh, I didn't know that in a map control like with OpenLayers, an iframe is created, To be sure, could you maybe take a look at this example? OpenLayers is used in combination with OSM tiles, similar to the usage of my application:
[http://wiki.openstreetmap.org/wiki/OpenLayers_Simple_Example](url)
Even though there doesn't seem to be any workaround, I am glad to know about the technical background, thanks.
