### ISSUE TITLE
can not resize when into the iframe area?

### ISSUE THREAD

**Issue by hurui1987** [RickStrahl/jquery-resizable#26]
iframe content in left and right panel

**Comment by RickStrahl** [comment]
There are big problems with iFrames because they steal focus. I suspect the slider works if you can keep the splitter element focused while dragging but it is slow.

iFrames are terrible for this use case - even a single one on either side is nearly unusable.

Sorry I don't know if there is a workaround for this.

**Comment by jeremymouton** [comment]
Here is my solution using CSS `pointer-events`.

```js
$('.box').resizable({
  handleSelector: '.splitter',
  resizeHeight: false,
  onDragStart: () => {
    // Iframes hijack cursor focus, so we disable pointer-events on drag
    $('iframe').css('pointer-events', 'none');
  },
  onDragEnd: () => {
    // Enable pointer-events 
    $('iframe').css('pointer-events', 'auto');
  },
});
```
